import type { AdminDashboardSnapshot } from './adminData';

export const fixtureAdminSnapshot: AdminDashboardSnapshot = {
  auditEvents: [
    {
      action: 'Accepted 12 profile changes',
      actor: 'Maya Chen',
      id: 'audit-profile-changes',
      target: 'Desktop Workstation',
      time: '09:42',
    },
    {
      action: 'Issued fresh cursor',
      actor: 'System',
      id: 'audit-fresh-cursor',
      target: 'JoeSSH Mobile',
      time: '09:38',
    },
    {
      action: 'Changed Jordan Lee role',
      actor: 'Noah Singh',
      id: 'audit-role-changed',
      target: 'Support Viewer',
      time: '09:21',
    },
    {
      action: 'Blocked export from unmanaged device',
      actor: 'Policy',
      id: 'audit-export-blocked',
      target: 'Unknown browser',
      time: '09:04',
    },
  ],
  devices: [
    {
      cursor: 'server-128',
      id: 'desktop-primary',
      lastSeen: '2 min ago',
      name: 'Desktop Workstation',
      owner: 'Maya Chen',
      platform: 'desktop',
      status: 'current',
    },
    {
      cursor: 'server-126',
      id: 'mobile-primary',
      lastSeen: '8 min ago',
      name: 'JoeSSH Mobile',
      owner: 'Eli Park',
      platform: 'ios',
      status: 'catching_up',
    },
    {
      cursor: 'server-120',
      id: 'tablet-field',
      lastSeen: '4 min ago',
      name: 'Field Tablet',
      owner: 'Riley Brooks',
      platform: 'android',
      status: 'degraded',
    },
    {
      cursor: 'server-90',
      id: 'laptop-archive',
      lastSeen: '2 hr ago',
      name: 'Archive Laptop',
      owner: 'Jordan Lee',
      platform: 'desktop',
      status: 'offline',
    },
    {
      cursor: 'server-128',
      id: 'web-admin',
      lastSeen: 'Live',
      name: 'Browser Admin',
      owner: 'Ops Team',
      platform: 'web',
      status: 'current',
    },
  ],
  members: [
    {
      deviceCount: 2,
      email: 'maya@atlasterm.dev',
      id: 'member-maya',
      name: 'Maya Chen',
      role: 'Workspace Admin',
      status: 'active',
    },
    {
      deviceCount: 1,
      email: 'noah@atlasterm.dev',
      id: 'member-noah',
      name: 'Noah Singh',
      role: 'Operator',
      status: 'active',
    },
    {
      deviceCount: 0,
      email: 'jordan@atlasterm.dev',
      id: 'member-jordan',
      name: 'Jordan Lee',
      role: 'Support Viewer',
      status: 'invited',
    },
    {
      deviceCount: 1,
      email: 'riley@atlasterm.dev',
      id: 'member-riley',
      name: 'Riley Brooks',
      role: 'Field Operator',
      status: 'suspended',
    },
  ],
  metrics: {
    activeMembers: 2,
    auditEventsToday: 18,
    healthyDevices: 3,
    rolesConfigured: 3,
  },
  roles: [
    {
      id: 'workspace-admin',
      memberCount: 1,
      name: 'Workspace Admin',
      risk: 'full',
      scope: 'Members, roles, sync policy',
    },
    {
      id: 'operator',
      memberCount: 1,
      name: 'Operator',
      risk: 'elevated',
      scope: 'Devices, sessions, audit read',
    },
    {
      id: 'support-viewer',
      memberCount: 1,
      name: 'Support Viewer',
      risk: 'limited',
      scope: 'Read-only dashboard access',
    },
  ],
};
