import {
  type AtlasLocale,
  createTranslator,
  detectAtlasLocale,
  getBrowserLocaleCandidates,
  getTextDirection,
  loadLocale,
  resolveAtlasLocale,
} from '@atlasterm/i18n';

export type LanguageChoice = AtlasLocale | 'auto';

const LANGUAGE_STORAGE_KEY = 'atlasterm.web.language';
const SHARED_FALLBACK_LOCALE: AtlasLocale = 'en';

const commonMessages = {
  'web.nav.team': 'Team',
  'web.language.status': 'Interface language',
  'web.language.currentPrefix': 'Current',
  'web.language.commonEntry': 'More global languages are listed in the selector',
  'web.nav.sync': 'Sync',
  'web.nav.devices': 'Devices',
  'web.nav.audit': 'Audit',
  'web.nav.storage': 'Storage',
  'web.table.teamMembers': 'Team members',
  'web.source.fixture': 'Fixture fallback',
  'web.source.live': 'Live snapshot',
  'web.snapshot.status': 'Snapshot status',
  'web.snapshot.mode': 'Mode',
  'web.snapshot.endpoint': 'Endpoint',
  'web.snapshot.lastRefreshed': 'Last refreshed',
  'web.snapshot.lastSuccess': 'Last successful refresh',
  'web.snapshot.notRefreshed': 'Not refreshed yet',
  'web.snapshot.fixtureEndpoint': 'Built-in fixture',
  'web.snapshot.health.ready': 'Healthy',
  'web.snapshot.health.loading': 'Refreshing',
  'web.snapshot.health.authRequired': 'Auth required',
  'web.snapshot.health.empty': 'Empty',
  'web.snapshot.health.error': 'Unhealthy',
  'web.state.auth.label': 'Authentication required',
  'web.state.auth.title': 'Sign in before viewing sync data',
  'web.state.auth.message': 'Authentication is required before sync data can be shown.',
  'web.state.empty.label': 'Empty snapshot',
  'web.state.empty.title': 'No admin sync data yet',
  'web.state.empty.message': 'No team sync data is available yet.',
  'web.state.error.label': 'Snapshot unavailable',
  'web.state.error.title': 'Admin snapshot could not be loaded',
  'web.state.error.message': 'Try refreshing or check the configured admin snapshot endpoint.',
  'web.state.loading.label': 'Loading snapshot',
  'web.state.loading.title': 'Loading admin dashboard',
  'web.state.loading.message': 'JoeSSH is fetching team, device, role, and audit state.',
  'web.status.current': 'Current',
  'web.status.catchingUp': 'Catching up',
  'web.status.degraded': 'Degraded',
  'web.status.offline': 'Offline',
  'web.status.live': 'Live',
  'web.status.active': 'Active',
  'web.status.invited': 'Invited',
  'web.status.suspended': 'Suspended',
  'web.role.workspaceAdmin': 'Workspace Admin',
  'web.role.operator': 'Operator',
  'web.role.supportViewer': 'Support Viewer',
  'web.scope.admin': 'Members, roles, sync policy',
  'web.scope.operator': 'Devices, sessions, audit read',
  'web.scope.viewer': 'Read-only dashboard access',
  'web.risk.full': 'Full access',
  'web.risk.elevated': 'Elevated',
  'web.risk.limited': 'Limited',
  'web.memberCount.one': 'member',
  'web.memberCount.other': 'members',
  'web.event.profileChanges': 'Accepted 12 profile changes',
  'web.event.freshCursor': 'Issued fresh cursor',
  'web.event.roleChanged': 'Changed Jordan Lee role',
  'web.event.exportBlocked': 'Blocked export from unmanaged device',
  'web.target.supportViewer': 'Support Viewer',
  'web.target.unknownBrowser': 'Unknown browser',
  'web.error.boundary.title': 'Something went wrong',
  'web.error.boundary.reload': 'Reload',

  'web.error.boundary.message': 'Reload JoeSSH or contact support if the issue continues.',
} as const;

export type LocalMessageKey = keyof typeof commonMessages;

type LocalMessageMap = Partial<Record<LocalMessageKey, string>>;

const localMessages: Record<AtlasLocale, LocalMessageMap> = {
  'zh-CN': {
    'web.snapshot.status': '\u5feb\u7167\u72b6\u6001',
    'web.snapshot.mode': '\u6570\u636e\u6a21\u5f0f',
    'web.snapshot.endpoint': '\u6570\u636e\u7aef\u70b9',
    'web.snapshot.lastRefreshed': '\u6700\u8fd1\u5237\u65b0',
    'web.snapshot.lastSuccess': '\u6700\u8fd1\u6210\u529f\u5237\u65b0',
    'web.snapshot.notRefreshed': '\u5c1a\u672a\u5237\u65b0',
    'web.snapshot.fixtureEndpoint': '\u5185\u7f6e\u6f14\u793a\u6570\u636e',
    'web.snapshot.health.ready': '\u5065\u5eb7',
    'web.snapshot.health.loading': '\u5237\u65b0\u4e2d',
    'web.snapshot.health.authRequired': '\u9700\u8981\u8ba4\u8bc1',
    'web.snapshot.health.empty': '\u6682\u65e0\u6570\u636e',
    'web.snapshot.health.error': '\u5f02\u5e38',
    'web.nav.team': '团队',
    'web.language.status': '界面语言',
    'web.language.currentPrefix': '当前',
    'web.language.commonEntry': '选择器中已列出更多全球常用语言',
    'web.nav.sync': '同步',
    'web.nav.devices': '设备',
    'web.nav.audit': '审计',
    'web.nav.storage': '存储',
    'web.table.teamMembers': '团队成员',
    'web.source.fixture': '演示数据回退',
    'web.source.live': '实时快照',
    'web.state.auth.label': '需要身份验证',
    'web.state.auth.title': '请先登录再查看同步数据',
    'web.state.auth.message': '通过身份验证后才会显示同步数据。',
    'web.state.empty.label': '快照为空',
    'web.state.empty.title': '尚无管理同步数据',
    'web.state.empty.message': '团队同步数据出现后会显示在这里。',
    'web.state.error.label': '快照不可用',
    'web.state.error.title': '无法加载管理快照',
    'web.state.error.message': '请刷新或检查管理快照端点配置。',
    'web.state.loading.label': '正在加载快照',
    'web.state.loading.title': '正在加载管理看板',
    'web.state.loading.message': 'JoeSSH 正在获取团队、设备、角色和审计状态。',
    'web.status.current': '最新',
    'web.status.catchingUp': '同步中',
    'web.status.degraded': '降级',
    'web.status.offline': '离线',
    'web.status.live': '实时',
    'web.status.active': '活跃',
    'web.status.invited': '已邀请',
    'web.status.suspended': '已停权',
    'web.role.workspaceAdmin': '工作区管理员',
    'web.role.operator': '运维操作员',
    'web.role.supportViewer': '支持查看者',
    'web.scope.admin': '成员、角色、同步策略',
    'web.scope.operator': '设备、会话、审计只读',
    'web.scope.viewer': '只读管理台访问',
    'web.risk.full': '完全访问',
    'web.risk.elevated': '高权限',
    'web.risk.limited': '受限',
    'web.memberCount.one': '名成员',
    'web.memberCount.other': '名成员',
    'web.event.profileChanges': '接受 12 项配置变更',
    'web.event.freshCursor': '签发新的同步游标',
    'web.event.roleChanged': '调整 Jordan Lee 的角色',
    'web.event.exportBlocked': '阻止未受管设备导出',
    'web.target.supportViewer': '支持查看者',
    'web.target.unknownBrowser': '未知浏览器',
    'web.error.boundary.title': '出现错误',
    'web.error.boundary.reload': '重新加载',

    'web.error.boundary.message': '\u8bf7\u91cd\u65b0\u52a0\u8f7d JoeSSH\uff1b\u5982\u679c\u95ee\u9898\u4ecd\u7136\u5b58\u5728\uff0c\u8bf7\u8054\u7cfb\u652f\u6301\u3002',
  },
  'zh-TW': {
    'web.snapshot.status': '\u5feb\u7167\u72c0\u614b',
    'web.snapshot.mode': '\u8cc7\u6599\u6a21\u5f0f',
    'web.snapshot.endpoint': '\u8cc7\u6599\u7aef\u9ede',
    'web.snapshot.lastRefreshed': '\u6700\u8fd1\u66f4\u65b0',
    'web.snapshot.lastSuccess': '\u6700\u8fd1\u6210\u529f\u66f4\u65b0',
    'web.snapshot.notRefreshed': '\u5c1a\u672a\u66f4\u65b0',
    'web.snapshot.fixtureEndpoint': '\u5167\u5efa\u793a\u7bc4\u8cc7\u6599',
    'web.snapshot.health.ready': '\u5065\u5eb7',
    'web.snapshot.health.loading': '\u66f4\u65b0\u4e2d',
    'web.snapshot.health.authRequired': '\u9700\u8981\u9a57\u8b49',
    'web.snapshot.health.empty': '\u66ab\u7121\u8cc7\u6599',
    'web.snapshot.health.error': '\u7570\u5e38',
    'web.nav.team': '團隊',
    'web.language.status': '介面語言',
    'web.language.currentPrefix': '目前',
    'web.language.commonEntry': '選單中已列出更多全球常用語言',
    'web.nav.sync': '同步',
    'web.nav.devices': '裝置',
    'web.nav.audit': '稽核',
    'web.nav.storage': '儲存',
    'web.table.teamMembers': '團隊成員',
    'web.source.fixture': '示範資料回退',
    'web.source.live': '即時快照',
    'web.state.auth.label': '需要驗證',
    'web.state.auth.title': '請先登入再查看同步資料',
    'web.state.auth.message': '完成驗證後才會顯示同步資料。',
    'web.state.empty.label': '快照為空',
    'web.state.empty.title': '尚無管理同步資料',
    'web.state.empty.message': '團隊同步資料出現後會顯示在這裡。',
    'web.state.error.label': '快照不可用',
    'web.state.error.title': '無法載入管理快照',
    'web.state.error.message': '請重新整理或檢查管理快照端點設定。',
    'web.state.loading.label': '正在載入快照',
    'web.state.loading.title': '正在載入管理看板',
    'web.state.loading.message': 'JoeSSH 正在取得團隊、裝置、角色與稽核狀態。',
    'web.status.current': '最新',
    'web.status.catchingUp': '同步中',
    'web.status.degraded': '降級',
    'web.status.offline': '離線',
    'web.status.live': '即時',
    'web.status.active': '啟用',
    'web.status.invited': '已邀請',
    'web.status.suspended': '已停權',
    'web.role.workspaceAdmin': '工作區管理員',
    'web.role.operator': '操作員',
    'web.role.supportViewer': '支援檢視者',
    'web.scope.admin': '成員、角色、同步政策',
    'web.scope.operator': '裝置、工作階段、稽核唯讀',
    'web.scope.viewer': '唯讀管理台存取',
    'web.risk.full': '完整存取',
    'web.risk.elevated': '高權限',
    'web.risk.limited': '受限',
    'web.memberCount.one': '位成員',
    'web.memberCount.other': '位成員',
    'web.event.profileChanges': '接受 12 項設定變更',
    'web.event.freshCursor': '簽發新的同步游標',
    'web.event.roleChanged': '調整 Jordan Lee 的角色',
    'web.event.exportBlocked': '阻止未受管裝置匯出',
    'web.target.supportViewer': '支援檢視者',
    'web.target.unknownBrowser': '未知瀏覽器',
    'web.error.boundary.title': '發生錯誤',
    'web.error.boundary.reload': '重新載入',

    'web.error.boundary.message': '\u8acb\u91cd\u65b0\u8f09\u5165 JoeSSH\uff1b\u5982\u679c\u554f\u984c\u4ecd\u7136\u5b58\u5728\uff0c\u8acb\u806f\u7d61\u652f\u63f4\u3002',
  },
  en: commonMessages,
  ja: {
    'web.nav.team': 'チーム',
    'web.nav.sync': '同期',
    'web.nav.devices': 'デバイス',
    'web.nav.audit': '監査',
    'web.nav.storage': 'ストレージ',
    'web.language.status': '表示言語',
    'web.language.currentPrefix': '現在',
    'web.language.commonEntry': '主要なグローバル言語はセレクターに表示されています',
    'web.table.teamMembers': 'チームメンバー',
    'web.source.fixture': 'フィクスチャフォールバック',
    'web.source.live': 'ライブスナップショット',
    'web.state.auth.label': '認証が必要',
    'web.state.auth.title': '同期データを表示する前にサインインしてください',
    'web.state.auth.message': '同期データを表示するには認証が必要です。',
    'web.state.empty.label': 'スナップショットが空',
    'web.state.empty.title': '管理者同期データがありません',
    'web.state.empty.message': 'チーム同期データがまだありません。',
    'web.state.error.label': 'スナップショット利用不可',
    'web.state.error.title': '管理者スナップショットを読み込めません',
    'web.state.error.message': '更新するか、管理者スナップショットエンドポイントを確認してください。',
    'web.state.loading.label': 'スナップショット読み込み中',
    'web.state.loading.title': '管理ダッシュボード読み込み中',
    'web.state.loading.message': 'JoeSSHがチーム、デバイス、役割、監査状態を取得中です。',
    'web.status.current': '最新',
    'web.status.catchingUp': '追従中',
    'web.status.degraded': '低下',
    'web.status.offline': 'オフライン',
    'web.status.live': 'ライブ',
    'web.status.active': 'アクティブ',
    'web.status.invited': '招待済み',
    'web.status.suspended': '停止中',
    'web.role.workspaceAdmin': 'ワークスペース管理者',
    'web.role.operator': 'オペレーター',
    'web.role.supportViewer': 'サポートビューア',
    'web.scope.admin': 'メンバー、役割、同期ポリシー',
    'web.scope.operator': 'デバイス、セッション、監査読み取り',
    'web.scope.viewer': '読み取り専用ダッシュボードアクセス',
    'web.risk.full': 'フルアクセス',
    'web.risk.elevated': '昇格',
    'web.risk.limited': '制限付き',
    'web.memberCount.one': 'メンバー',
    'web.memberCount.other': 'メンバー',
    'web.event.profileChanges': '12件のプロファイル変更を承認',
    'web.event.freshCursor': '新しいカーソルを発行',
    'web.event.roleChanged': 'Jordan Leeの役割を変更',
    'web.event.exportBlocked': '非管理デバイスからのエクスポートをブロック',
    'web.target.supportViewer': 'サポートビューア',
    'web.target.unknownBrowser': '不明なブラウザ',
    'web.error.boundary.title': 'エラーが発生しました',
    'web.error.boundary.reload': '再読み込み',

    'web.error.boundary.message': 'JoeSSH \u3092\u518d\u8aad\u307f\u8fbc\u307f\u3057\u3066\u304f\u3060\u3055\u3044\u3002\u554f\u984c\u304c\u7d9a\u304f\u5834\u5408\u306f\u30b5\u30dd\u30fc\u30c8\u306b\u304a\u554f\u3044\u5408\u308f\u305b\u304f\u3060\u3055\u3044\u3002',
  },
  ko: {
    'web.nav.team': '팀',
    'web.nav.sync': '동기화',
    'web.nav.devices': '장치',
    'web.nav.audit': '감사',
    'web.nav.storage': '스토리지',
    'web.language.status': '표시 언어',
    'web.language.currentPrefix': '현재',
    'web.language.commonEntry': '주요 글로벌 언어는 선택 목록에 있습니다',
    'web.table.teamMembers': '팀 멤버',
    'web.source.fixture': '픽스처 폴백',
    'web.source.live': '라이브 스냅샷',
    'web.state.auth.label': '인증 필요',
    'web.state.auth.title': '동기화 데이터를 보려면 로그인하세요',
    'web.state.auth.message': '동기화 데이터를 표시하려면 인증이 필요합니다.',
    'web.state.empty.label': '빈 스냅샷',
    'web.state.empty.title': '관리 동기화 데이터 없음',
    'web.state.empty.message': '팀 동기화 데이터가 아직 없습니다.',
    'web.state.error.label': '스냅샷 사용 불가',
    'web.state.error.title': '관리 스냅샷을 로드할 수 없습니다',
    'web.state.error.message': '새로고침하거나 관리 스냅샷 엔드포인트를 확인하세요.',
    'web.state.loading.label': '스냅샷 로딩 중',
    'web.state.loading.title': '관리 대시보드 로딩 중',
    'web.state.loading.message': 'JoeSSH이 팀, 장치, 역할, 감사 상태를 가져오는 중입니다.',
    'web.status.current': '최신',
    'web.status.catchingUp': '동기화 중',
    'web.status.degraded': '성능 저하',
    'web.status.offline': '오프라인',
    'web.status.live': '실시간',
    'web.status.active': '활성',
    'web.status.invited': '초대됨',
    'web.status.suspended': '정지됨',
    'web.role.workspaceAdmin': '워크스페이스 관리자',
    'web.role.operator': '운영자',
    'web.role.supportViewer': '지원 뷰어',
    'web.scope.admin': '멤버, 역할, 동기화 정책',
    'web.scope.operator': '장치, 세션, 감사 읽기',
    'web.scope.viewer': '읽기 전용 대시보드 접근',
    'web.risk.full': '전체 접근',
    'web.risk.elevated': '상승',
    'web.risk.limited': '제한됨',
    'web.memberCount.one': '명',
    'web.memberCount.other': '명',
    'web.event.profileChanges': '12개 프로필 변경 수락',
    'web.event.freshCursor': '새 커서 발급',
    'web.event.roleChanged': 'Jordan Lee 역할 변경',
    'web.event.exportBlocked': '비관리 장치에서 내보내기 차단',
    'web.target.supportViewer': '지원 뷰어',
    'web.target.unknownBrowser': '알 수 없는 브라우저',
    'web.error.boundary.title': '오류가 발생했습니다',
    'web.error.boundary.reload': '새로고침',

    'web.error.boundary.message': 'JoeSSH\uc744 \ub2e4\uc2dc \ub85c\ub4dc\ud558\uc138\uc694. \ubb38\uc81c\uac00 \uacc4\uc18d\ub418\uba74 \uc9c0\uc6d0\ud300\uc5d0 \ubb38\uc758\ud558\uc138\uc694.',
  },
  es: {
    'web.nav.team': 'Equipo',
    'web.nav.sync': 'Sincronización',
    'web.nav.devices': 'Dispositivos',
    'web.nav.audit': 'Auditoría',
    'web.nav.storage': 'Almacenamiento',
    'web.language.status': 'Idioma de interfaz',
    'web.language.currentPrefix': 'Actual',
    'web.language.commonEntry': 'El selector incluye más idiomas globales comunes',
    'web.table.teamMembers': 'Miembros del equipo',
    'web.source.fixture': 'Respaldo de demostración',
    'web.source.live': 'Instantánea en vivo',
    'web.state.auth.label': 'Autenticación requerida',
    'web.state.auth.title': 'Inicie sesión antes de ver los datos de sincronización',
    'web.state.auth.message': 'Se requiere autenticación antes de mostrar los datos de sincronización.',
    'web.state.empty.label': 'Instantánea vacía',
    'web.state.empty.title': 'Sin datos de sincronización aún',
    'web.state.empty.message': 'No hay datos de sincronización del equipo disponibles aún.',
    'web.state.error.label': 'Instantánea no disponible',
    'web.state.error.title': 'No se pudo cargar la instantánea de administración',
    'web.state.error.message': 'Intente actualizar o verifique el endpoint de instantánea configurado.',
    'web.state.loading.label': 'Cargando instantánea',
    'web.state.loading.title': 'Cargando panel de administración',
    'web.state.loading.message': 'JoeSSH está obteniendo el estado del equipo, dispositivos, roles y auditoría.',
    'web.status.current': 'Actual',
    'web.status.catchingUp': 'Sincronizando',
    'web.status.degraded': 'Degradado',
    'web.status.offline': 'Desconectado',
    'web.status.live': 'En vivo',
    'web.status.active': 'Activo',
    'web.status.invited': 'Invitado',
    'web.status.suspended': 'Suspendido',
    'web.role.workspaceAdmin': 'Administrador del espacio',
    'web.role.operator': 'Operador',
    'web.role.supportViewer': 'Visor de soporte',
    'web.scope.admin': 'Miembros, roles, política de sincronización',
    'web.scope.operator': 'Dispositivos, sesiones, lectura de auditoría',
    'web.scope.viewer': 'Acceso de solo lectura al panel',
    'web.risk.full': 'Acceso completo',
    'web.risk.elevated': 'Elevado',
    'web.risk.limited': 'Limitado',
    'web.memberCount.one': 'miembro',
    'web.memberCount.other': 'miembros',
    'web.event.profileChanges': 'Aceptó 12 cambios de perfil',
    'web.event.freshCursor': 'Emisión de cursor nuevo',
    'web.event.roleChanged': 'Cambió el rol de Jordan Lee',
    'web.event.exportBlocked': 'Bloqueó exportación desde dispositivo no administrado',
    'web.target.supportViewer': 'Visor de soporte',
    'web.target.unknownBrowser': 'Navegador desconocido',
    'web.error.boundary.title': 'Algo salió mal',
    'web.error.boundary.reload': 'Recargar',

    'web.error.boundary.message': 'Recarga JoeSSH o contacta con soporte si el problema contin\u00faa.',
  },
  fr: {
    'web.nav.team': 'Équipe',
    'web.nav.sync': 'Synchronisation',
    'web.nav.devices': 'Appareils',
    'web.nav.audit': 'Audit',
    'web.nav.storage': 'Stockage',
    'web.language.status': 'Langue de l\'interface',
    'web.language.currentPrefix': 'Actuel',
    'web.language.commonEntry': 'Le sélecteur liste d\'autres langues mondiales courantes',
    'web.table.teamMembers': 'Membres de l\'équipe',
    'web.source.fixture': 'Repli de démonstration',
    'web.source.live': 'Instantané en direct',
    'web.state.auth.label': 'Authentification requise',
    'web.state.auth.title': 'Connectez-vous avant de consulter les données de synchronisation',
    'web.state.auth.message': 'L\'authentification est requise avant d\'afficher les données de synchronisation.',
    'web.state.empty.label': 'Instantané vide',
    'web.state.empty.title': 'Pas encore de données de synchronisation',
    'web.state.empty.message': 'Aucune donnée de synchronisation d\'équipe n\'est encore disponible.',
    'web.state.error.label': 'Instantané indisponible',
    'web.state.error.title': 'Impossible de charger l\'instantané d\'administration',
    'web.state.error.message': 'Essayez de rafraîchir ou vérifiez le point de terminaison configuré.',
    'web.state.loading.label': 'Chargement de l\'instantané',
    'web.state.loading.title': 'Chargement du tableau de bord',
    'web.state.loading.message': 'JoeSSH récupère l\'état de l\'équipe, des appareils, des rôles et de l\'audit.',
    'web.status.current': 'À jour',
    'web.status.catchingUp': 'Synchronisation',
    'web.status.degraded': 'Dégradé',
    'web.status.offline': 'Hors ligne',
    'web.status.live': 'En direct',
    'web.status.active': 'Actif',
    'web.status.invited': 'Invité',
    'web.status.suspended': 'Suspendu',
    'web.role.workspaceAdmin': 'Administrateur de l\'espace',
    'web.role.operator': 'Opérateur',
    'web.role.supportViewer': 'Visualiseur de support',
    'web.scope.admin': 'Membres, rôles, politique de synchronisation',
    'web.scope.operator': 'Appareils, sessions, lecture d\'audit',
    'web.scope.viewer': 'Accès en lecture seule au tableau de bord',
    'web.risk.full': 'Accès complet',
    'web.risk.elevated': 'Élevé',
    'web.risk.limited': 'Limité',
    'web.memberCount.one': 'membre',
    'web.memberCount.other': 'membres',
    'web.event.profileChanges': 'Accepté 12 modifications de profil',
    'web.event.freshCursor': 'Nouveau curseur émis',
    'web.event.roleChanged': 'Rôle de Jordan Lee modifié',
    'web.event.exportBlocked': 'Exportation bloquée depuis un appareil non géré',
    'web.target.supportViewer': 'Visualiseur de support',
    'web.target.unknownBrowser': 'Navigateur inconnu',
    'web.error.boundary.title': 'Une erreur est survenue',
    'web.error.boundary.reload': 'Recharger',

    'web.error.boundary.message': 'Rechargez JoeSSH ou contactez le support si le probl\u00e8me persiste.',
  },
  de: {
    'web.nav.team': 'Team',
    'web.nav.sync': 'Synchronisation',
    'web.nav.devices': 'Geräte',
    'web.nav.audit': 'Prüfung',
    'web.nav.storage': 'Speicher',
    'web.language.status': 'Oberflächensprache',
    'web.language.currentPrefix': 'Aktuell',
    'web.language.commonEntry': 'Weitere gängige Weltsprachen stehen in der Auswahl',
    'web.table.teamMembers': 'Teammitglieder',
    'web.source.fixture': 'Demo-Daten-Fallback',
    'web.source.live': 'Live-Schnappschuss',
    'web.state.auth.label': 'Authentifizierung erforderlich',
    'web.state.auth.title': 'Melden Sie sich an, bevor Sie Synchronisationsdaten anzeigen',
    'web.state.auth.message': 'Vor der Anzeige von Synchronisationsdaten ist eine Authentifizierung erforderlich.',
    'web.state.empty.label': 'Leerer Schnappschuss',
    'web.state.empty.title': 'Noch keine Synchronisationsdaten',
    'web.state.empty.message': 'Es sind noch keine Team-Synchronisationsdaten verfügbar.',
    'web.state.error.label': 'Schnappschuss nicht verfügbar',
    'web.state.error.title': 'Admin-Schnappschuss konnte nicht geladen werden',
    'web.state.error.message': 'Versuchen Sie zu aktualisieren oder prüfen Sie den konfigurierten Endpunkt.',
    'web.state.loading.label': 'Schnappschuss wird geladen',
    'web.state.loading.title': 'Admin-Dashboard wird geladen',
    'web.state.loading.message': 'JoeSSH ruft Team-, Geräte-, Rollen- und Prüfstatus ab.',
    'web.status.current': 'Aktuell',
    'web.status.catchingUp': 'Synchronisierung',
    'web.status.degraded': 'Eingeschränkt',
    'web.status.offline': 'Offline',
    'web.status.live': 'Live',
    'web.status.active': 'Aktiv',
    'web.status.invited': 'Eingeladen',
    'web.status.suspended': 'Gesperrt',
    'web.role.workspaceAdmin': 'Workspace-Administrator',
    'web.role.operator': 'Betreiber',
    'web.role.supportViewer': 'Support-Betrachter',
    'web.scope.admin': 'Mitglieder, Rollen, Synchronisationsrichtlinie',
    'web.scope.operator': 'Geräte, Sitzungen, Prüflesezugriff',
    'web.scope.viewer': 'Schreibgeschützter Dashboard-Zugriff',
    'web.risk.full': 'Voller Zugriff',
    'web.risk.elevated': 'Erhöht',
    'web.risk.limited': 'Eingeschränkt',
    'web.memberCount.one': 'Mitglied',
    'web.memberCount.other': 'Mitglieder',
    'web.event.profileChanges': '12 Profiländerungen akzeptiert',
    'web.event.freshCursor': 'Neuen Cursor ausgestellt',
    'web.event.roleChanged': 'Jordan Lee Rolle geändert',
    'web.event.exportBlocked': 'Export von nicht verwaltetem Gerät blockiert',
    'web.target.supportViewer': 'Support-Betrachter',
    'web.target.unknownBrowser': 'Unbekannter Browser',
    'web.error.boundary.title': 'Etwas ist schiefgelaufen',
    'web.error.boundary.reload': 'Neu laden',

    'web.error.boundary.message': 'Laden Sie JoeSSH neu oder wenden Sie sich an den Support, wenn das Problem weiterhin besteht.',
  },
  'pt-BR': {
    'web.nav.team': 'Equipe',
    'web.nav.sync': 'Sincronização',
    'web.nav.devices': 'Dispositivos',
    'web.nav.audit': 'Auditoria',
    'web.nav.storage': 'Armazenamento',
    'web.language.status': 'Idioma da interface',
    'web.language.currentPrefix': 'Atual',
    'web.language.commonEntry': 'O seletor lista outros idiomas globais comuns',
    'web.table.teamMembers': 'Membros da equipe',
    'web.source.fixture': 'Fallback de demonstração',
    'web.source.live': 'Instantâneo ao vivo',
    'web.state.auth.label': 'Autenticação necessária',
    'web.state.auth.title': 'Faça login antes de visualizar os dados de sincronização',
    'web.state.auth.message': 'A autenticação é necessária antes de exibir os dados de sincronização.',
    'web.state.empty.label': 'Instantâneo vazio',
    'web.state.empty.title': 'Sem dados de sincronização ainda',
    'web.state.empty.message': 'Nenhum dado de sincronização da equipe disponível ainda.',
    'web.state.error.label': 'Instantâneo indisponível',
    'web.state.error.title': 'Não foi possível carregar o instantâneo de administração',
    'web.state.error.message': 'Tente atualizar ou verifique o endpoint configurado.',
    'web.state.loading.label': 'Carregando instantâneo',
    'web.state.loading.title': 'Carregando painel de administração',
    'web.state.loading.message': 'JoeSSH está obtendo o estado da equipe, dispositivos, funções e auditoria.',
    'web.status.current': 'Atual',
    'web.status.catchingUp': 'Sincronizando',
    'web.status.degraded': 'Degradado',
    'web.status.offline': 'Offline',
    'web.status.live': 'Ao vivo',
    'web.status.active': 'Ativo',
    'web.status.invited': 'Convidado',
    'web.status.suspended': 'Suspenso',
    'web.role.workspaceAdmin': 'Administrador do espaço',
    'web.role.operator': 'Operador',
    'web.role.supportViewer': 'Visualizador de suporte',
    'web.scope.admin': 'Membros, funções, política de sincronização',
    'web.scope.operator': 'Dispositivos, sessões, leitura de auditoria',
    'web.scope.viewer': 'Acesso somente leitura ao painel',
    'web.risk.full': 'Acesso completo',
    'web.risk.elevated': 'Elevado',
    'web.risk.limited': 'Limitado',
    'web.memberCount.one': 'membro',
    'web.memberCount.other': 'membros',
    'web.event.profileChanges': 'Aceitou 12 alterações de perfil',
    'web.event.freshCursor': 'Novo cursor emitido',
    'web.event.roleChanged': 'Alterou a função de Jordan Lee',
    'web.event.exportBlocked': 'Bloqueou exportação de dispositivo não gerenciado',
    'web.target.supportViewer': 'Visualizador de suporte',
    'web.target.unknownBrowser': 'Navegador desconhecido',
    'web.error.boundary.title': 'Algo deu errado',
    'web.error.boundary.reload': 'Recarregar',

    'web.error.boundary.message': 'Recarregue o JoeSSH ou contate o suporte se o problema continuar.',
  },
  ru: {
    'web.nav.team': 'Команда',
    'web.nav.sync': 'Синхронизация',
    'web.nav.devices': 'Устройства',
    'web.nav.audit': 'Аудит',
    'web.nav.storage': 'Хранилище',
    'web.language.status': 'Язык интерфейса',
    'web.language.currentPrefix': 'Текущий',
    'web.language.commonEntry': 'В списке доступны другие распространенные языки',
    'web.table.teamMembers': 'Члены команды',
    'web.source.fixture': 'Демо-данные',
    'web.source.live': 'Снимок в реальном времени',
    'web.state.auth.label': 'Требуется аутентификация',
    'web.state.auth.title': 'Войдите перед просмотром данных синхронизации',
    'web.state.auth.message': 'Для отображения данных синхронизации требуется аутентификация.',
    'web.state.empty.label': 'Пустой снимок',
    'web.state.empty.title': 'Данные синхронизации пока отсутствуют',
    'web.state.empty.message': 'Данные синхронизации команды пока недоступны.',
    'web.state.error.label': 'Снимок недоступен',
    'web.state.error.title': 'Не удалось загрузить снимок администратора',
    'web.state.error.message': 'Попробуйте обновить или проверьте настроенный endpoint.',
    'web.state.loading.label': 'Загрузка снимка',
    'web.state.loading.title': 'Загрузка панели администратора',
    'web.state.loading.message': 'JoeSSH получает состояние команды, устройств, ролей и аудита.',
    'web.status.current': 'Актуальный',
    'web.status.catchingUp': 'Синхронизация',
    'web.status.degraded': 'Снижен',
    'web.status.offline': 'Не в сети',
    'web.status.live': 'В реальном времени',
    'web.status.active': 'Активный',
    'web.status.invited': 'Приглашён',
    'web.status.suspended': 'Приостановлен',
    'web.role.workspaceAdmin': 'Администратор пространства',
    'web.role.operator': 'Оператор',
    'web.role.supportViewer': 'Наблюдатель поддержки',
    'web.scope.admin': 'Участники, роли, политика синхронизации',
    'web.scope.operator': 'Устройства, сессии, чтение аудита',
    'web.scope.viewer': 'Доступ только для чтения к панели',
    'web.risk.full': 'Полный доступ',
    'web.risk.elevated': 'Повышенный',
    'web.risk.limited': 'Ограниченный',
    'web.memberCount.one': 'участник',
    'web.memberCount.other': 'участников',
    'web.event.profileChanges': 'Принято 12 изменений профиля',
    'web.event.freshCursor': 'Выпущен новый курсор',
    'web.event.roleChanged': 'Изменена роль Jordan Lee',
    'web.event.exportBlocked': 'Блокирован экспорт с неуправляемого устройства',
    'web.target.supportViewer': 'Наблюдатель поддержки',
    'web.target.unknownBrowser': 'Неизвестный браузер',
    'web.error.boundary.title': 'Произошла ошибка',
    'web.error.boundary.reload': 'Перезагрузить',

    'web.error.boundary.message': '\u041f\u0435\u0440\u0435\u0437\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u0435 JoeSSH \u0438\u043b\u0438 \u043e\u0431\u0440\u0430\u0442\u0438\u0442\u0435\u0441\u044c \u0432 \u043f\u043e\u0434\u0434\u0435\u0440\u0436\u043a\u0443, \u0435\u0441\u043b\u0438 \u043f\u0440\u043e\u0431\u043b\u0435\u043c\u0430 \u043d\u0435 \u0438\u0441\u0447\u0435\u0437\u043d\u0435\u0442.',
  },
  ar: {
    'web.nav.team': 'الفريق',
    'web.nav.sync': 'المزامنة',
    'web.nav.devices': 'الأجهزة',
    'web.nav.audit': 'التدقيق',
    'web.nav.storage': 'التخزين',
    'web.language.status': 'لغة الواجهة',
    'web.language.currentPrefix': 'الحالية',
    'web.language.commonEntry': 'تتضمن القائمة لغات عالمية شائعة أخرى',
    'web.table.teamMembers': 'أعضاء الفريق',
    'web.source.fixture': 'بيانات تجريبية',
    'web.source.live': 'لقطة مباشرة',
    'web.state.auth.label': 'مطلوب مصادقة',
    'web.state.auth.title': 'سجّل الدخول قبل عرض بيانات المزامنة',
    'web.state.auth.message': 'المصادقة مطلوبة قبل عرض بيانات المزامنة.',
    'web.state.empty.label': 'لقطة فارغة',
    'web.state.empty.title': 'لا توجد بيانات مزامنة بعد',
    'web.state.empty.message': 'لا توجد بيانات مزامنة للفريق متاحة بعد.',
    'web.state.error.label': 'اللقطة غير متاحة',
    'web.state.error.title': 'تعذر تحميل لقطة المسؤول',
    'web.state.error.message': 'حاول التحديث أو تحقق من نقطة النهاية المُعدّة.',
    'web.state.loading.label': 'جارٍ تحميل اللقطة',
    'web.state.loading.title': 'جارٍ تحميل لوحة المسؤول',
    'web.state.loading.message': 'JoeSSH يجلب حالة الفريق والأجهزة والأدوار والتدقيق.',
    'web.status.current': 'الحالي',
    'web.status.catchingUp': 'جارٍ المزامنة',
    'web.status.degraded': 'متراجع',
    'web.status.offline': 'غير متصل',
    'web.status.live': 'مباشر',
    'web.status.active': 'نشط',
    'web.status.invited': 'مدعو',
    'web.status.suspended': 'معلّق',
    'web.role.workspaceAdmin': 'مدير مساحة العمل',
    'web.role.operator': 'مشغّل',
    'web.role.supportViewer': 'عارض الدعم',
    'web.scope.admin': 'الأعضاء، الأدوار، سياسة المزامنة',
    'web.scope.operator': 'الأجهزة، الجلسات، قراءة التدقيق',
    'web.scope.viewer': 'وصول للقراءة فقط للوحة',
    'web.risk.full': 'وصول كامل',
    'web.risk.elevated': 'مرتفع',
    'web.risk.limited': 'محدود',
    'web.memberCount.one': 'عضو',
    'web.memberCount.other': 'أعضاء',
    'web.event.profileChanges': 'قبول 12 تغييرًا في الملف الشخصي',
    'web.event.freshCursor': 'إصدار مؤشر جديد',
    'web.event.roleChanged': 'تغيير دور Jordan Lee',
    'web.event.exportBlocked': 'حظر التصدير من جهاز غير مُدار',
    'web.target.supportViewer': 'عارض الدعم',
    'web.target.unknownBrowser': 'متصفح غير معروف',
    'web.error.boundary.title': 'حدث خطأ ما',
    'web.error.boundary.reload': 'إعادة تحميل',

    'web.error.boundary.message': '\u0623\u0639\u062f \u062a\u062d\u0645\u064a\u0644 JoeSSH \u0623\u0648 \u062a\u0648\u0627\u0635\u0644 \u0645\u0639 \u0627\u0644\u062f\u0639\u0645 \u0625\u0630\u0627 \u0627\u0633\u062a\u0645\u0631\u062a \u0627\u0644\u0645\u0634\u0643\u0644\u0629.',
  },
  hi: {
    'web.nav.team': 'टीम',
    'web.nav.sync': 'सिंक',
    'web.nav.devices': 'उपकरण',
    'web.nav.audit': 'ऑडिट',
    'web.nav.storage': 'स्टोरेज',
    'web.language.status': 'इंटरफेस भाषा',
    'web.language.currentPrefix': 'वर्तमान',
    'web.language.commonEntry': 'चयन सूची में अन्य सामान्य वैश्विक भाषाएं हैं',
    'web.table.teamMembers': 'टीम सदस्य',
    'web.source.fixture': 'डेमो फॉलबैक',
    'web.source.live': 'लाइव स्नैपशॉट',
    'web.state.auth.label': 'प्रमाणीकरण आवश्यक',
    'web.state.auth.title': 'सिंक डेटा देखने से पहले साइन इन करें',
    'web.state.auth.message': 'सिंक डेटा प्रदर्शित करने से पहले प्रमाणीकरण आवश्यक है।',
    'web.state.empty.label': 'खाली स्नैपशॉट',
    'web.state.empty.title': 'अभी तक कोई सिंक डेटा नहीं',
    'web.state.empty.message': 'अभी तक कोई टीम सिंक डेटा उपलब्ध नहीं है।',
    'web.state.error.label': 'स्नैपशॉट अनुपलब्ध',
    'web.state.error.title': 'एडमिन स्नैपशॉट लोड नहीं हो सका',
    'web.state.error.message': 'रिफ्रेश करें या कॉन्फ़िगर किए गए एंडपॉइंट की जांच करें।',
    'web.state.loading.label': 'स्नैपशॉट लोड हो रहा है',
    'web.state.loading.title': 'एडमिन डैशबोर्ड लोड हो रहा है',
    'web.state.loading.message': 'JoeSSH टीम, उपकरण, भूमिकाएं और ऑडिट स्थिति प्राप्त कर रहा है।',
    'web.status.current': 'वर्तमान',
    'web.status.catchingUp': 'सिंक हो रहा है',
    'web.status.degraded': 'कमजोर',
    'web.status.offline': 'ऑफ़लाइन',
    'web.status.live': 'लाइव',
    'web.status.active': 'सक्रिय',
    'web.status.invited': 'आमंत्रित',
    'web.status.suspended': 'निलंबित',
    'web.role.workspaceAdmin': 'वर्कस्पेस एडमिन',
    'web.role.operator': 'ऑपरेटर',
    'web.role.supportViewer': 'सपोर्ट व्यूअर',
    'web.scope.admin': 'सदस्य, भूमिकाएं, सिंक नीति',
    'web.scope.operator': 'उपकरण, सत्र, ऑडिट रीड',
    'web.scope.viewer': 'केवल-पठन डैशबोर्ड एक्सेस',
    'web.risk.full': 'पूर्ण पहुंच',
    'web.risk.elevated': 'उन्नत',
    'web.risk.limited': 'सीमित',
    'web.memberCount.one': 'सदस्य',
    'web.memberCount.other': 'सदस्य',
    'web.event.profileChanges': '12 प्रोफ़ाइल परिवर्तन स्वीकार किए',
    'web.event.freshCursor': 'नया कर्सर जारी किया',
    'web.event.roleChanged': 'Jordan Lee की भूमिका बदली',
    'web.event.exportBlocked': 'गैर-प्रबंधित उपकरण से निर्यात अवरुद्ध',
    'web.target.supportViewer': 'सपोर्ट व्यूअर',
    'web.target.unknownBrowser': 'अज्ञात ब्राउज़र',
    'web.error.boundary.title': 'कुछ गलत हो गया',
    'web.error.boundary.reload': 'पुनः लोड करें',

    'web.error.boundary.message': 'JoeSSH \u0915\u094b \u092b\u093f\u0930 \u0938\u0947 \u0932\u094b\u0921 \u0915\u0930\u0947\u0902 \u092f\u093e \u0938\u092e\u0938\u094d\u092f\u093e \u091c\u093e\u0930\u0940 \u0930\u0939\u0928\u0947 \u092a\u0930 \u0938\u0939\u093e\u092f\u0924\u093e \u0938\u0947 \u0938\u0902\u092a\u0930\u094d\u0915 \u0915\u0930\u0947\u0902\u0964',
  },
  id: {
    'web.nav.team': 'Tim',
    'web.nav.sync': 'Sinkronisasi',
    'web.nav.devices': 'Perangkat',
    'web.nav.audit': 'Audit',
    'web.nav.storage': 'Penyimpanan',
    'web.language.status': 'Bahasa antarmuka',
    'web.language.currentPrefix': 'Saat ini',
    'web.language.commonEntry': 'Pemilih memuat bahasa global umum lainnya',
    'web.table.teamMembers': 'Anggota tim',
    'web.source.fixture': 'Fallback demo',
    'web.source.live': 'Snapshot langsung',
    'web.state.auth.label': 'Autentikasi diperlukan',
    'web.state.auth.title': 'Masuk sebelum melihat data sinkronisasi',
    'web.state.auth.message': 'Autentikasi diperlukan sebelum menampilkan data sinkronisasi.',
    'web.state.empty.label': 'Snapshot kosong',
    'web.state.empty.title': 'Belum ada data sinkronisasi',
    'web.state.empty.message': 'Data sinkronisasi tim belum tersedia.',
    'web.state.error.label': 'Snapshot tidak tersedia',
    'web.state.error.title': 'Snapshot admin gagal dimuat',
    'web.state.error.message': 'Coba segarkan atau periksa endpoint yang dikonfigurasi.',
    'web.state.loading.label': 'Memuat snapshot',
    'web.state.loading.title': 'Memuat dasbor admin',
    'web.state.loading.message': 'JoeSSH sedang mengambil status tim, perangkat, peran, dan audit.',
    'web.status.current': 'Terkini',
    'web.status.catchingUp': 'Menyinkronkan',
    'web.status.degraded': 'Menurun',
    'web.status.offline': 'Offline',
    'web.status.live': 'Langsung',
    'web.status.active': 'Aktif',
    'web.status.invited': 'Diundang',
    'web.status.suspended': 'Ditangguhkan',
    'web.role.workspaceAdmin': 'Admin ruang kerja',
    'web.role.operator': 'Operator',
    'web.role.supportViewer': 'Penampil dukungan',
    'web.scope.admin': 'Anggota, peran, kebijakan sinkronisasi',
    'web.scope.operator': 'Perangkat, sesi, baca audit',
    'web.scope.viewer': 'Akses dasbor hanya-baca',
    'web.risk.full': 'Akses penuh',
    'web.risk.elevated': 'Tinggi',
    'web.risk.limited': 'Terbatas',
    'web.memberCount.one': 'anggota',
    'web.memberCount.other': 'anggota',
    'web.event.profileChanges': 'Menerima 12 perubahan profil',
    'web.event.freshCursor': 'Menerbitkan kursor baru',
    'web.event.roleChanged': 'Mengubah peran Jordan Lee',
    'web.event.exportBlocked': 'Memblokir ekspor dari perangkat tidak dikelola',
    'web.target.supportViewer': 'Penampil dukungan',
    'web.target.unknownBrowser': 'Browser tidak dikenal',
    'web.error.boundary.title': 'Terjadi kesalahan',
    'web.error.boundary.reload': 'Muat ulang',

    'web.error.boundary.message': 'Muat ulang JoeSSH atau hubungi dukungan jika masalah berlanjut.',
  },
  vi: {
    'web.nav.team': 'Nhóm',
    'web.nav.sync': 'Đồng bộ',
    'web.nav.devices': 'Thiết bị',
    'web.nav.audit': 'Kiểm toán',
    'web.nav.storage': 'Lưu trữ',
    'web.language.status': 'Ngôn ngữ giao diện',
    'web.language.currentPrefix': 'Hiện tại',
    'web.language.commonEntry': 'Danh sách chọn có thêm các ngôn ngữ phổ biến',
    'web.table.teamMembers': 'Thành viên nhóm',
    'web.source.fixture': 'Dữ liệu demo',
    'web.source.live': 'Ảnh chụp trực tiếp',
    'web.state.auth.label': 'Cần xác thực',
    'web.state.auth.title': 'Đăng nhập trước khi xem dữ liệu đồng bộ',
    'web.state.auth.message': 'Cần xác thực trước khi hiển thị dữ liệu đồng bộ.',
    'web.state.empty.label': 'Ảnh chụp trống',
    'web.state.empty.title': 'Chưa có dữ liệu đồng bộ',
    'web.state.empty.message': 'Chưa có dữ liệu đồng bộ nhóm nào.',
    'web.state.error.label': 'Ảnh chụp không khả dụng',
    'web.state.error.title': 'Không thể tải ảnh chụp quản trị',
    'web.state.error.message': 'Thử làm mới hoặc kiểm tra endpoint đã cấu hình.',
    'web.state.loading.label': 'Đang tải ảnh chụp',
    'web.state.loading.title': 'Đang tải bảng điều khiển',
    'web.state.loading.message': 'JoeSSH đang lấy trạng thái nhóm, thiết bị, vai trò và kiểm toán.',
    'web.status.current': 'Hiện tại',
    'web.status.catchingUp': 'Đang đồng bộ',
    'web.status.degraded': 'Giảm hiệu suất',
    'web.status.offline': 'Ngoại tuyến',
    'web.status.live': 'Trực tiếp',
    'web.status.active': 'Hoạt động',
    'web.status.invited': 'Đã mời',
    'web.status.suspended': 'Tạm ngưng',
    'web.role.workspaceAdmin': 'Quản trị viên không gian',
    'web.role.operator': 'Vận hành viên',
    'web.role.supportViewer': 'Người xem hỗ trợ',
    'web.scope.admin': 'Thành viên, vai trò, chính sách đồng bộ',
    'web.scope.operator': 'Thiết bị, phiên, đọc kiểm toán',
    'web.scope.viewer': 'Truy cập bảng điều khiển chỉ đọc',
    'web.risk.full': 'Truy cập đầy đủ',
    'web.risk.elevated': 'Cao',
    'web.risk.limited': 'Hạn chế',
    'web.memberCount.one': 'thành viên',
    'web.memberCount.other': 'thành viên',
    'web.event.profileChanges': 'Chấp nhận 12 thay đổi hồ sơ',
    'web.event.freshCursor': 'Phát hành con trỏ mới',
    'web.event.roleChanged': 'Thay đổi vai trò Jordan Lee',
    'web.event.exportBlocked': 'Chặn xuất từ thiết bị không quản lý',
    'web.target.supportViewer': 'Người xem hỗ trợ',
    'web.target.unknownBrowser': 'Trình duyệt không xác định',
    'web.error.boundary.title': 'Đã xảy ra lỗi',
    'web.error.boundary.reload': 'Tải lại',

    'web.error.boundary.message': 'T\u1ea3i l\u1ea1i JoeSSH ho\u1eb7c li\u00ean h\u1ec7 h\u1ed7 tr\u1ee3 n\u1ebfu s\u1ef1 c\u1ed1 v\u1eabn ti\u1ebfp di\u1ec5n.',
  },
  th: {
    'web.nav.team': 'ทีม',
    'web.nav.sync': 'ซิงค์',
    'web.nav.devices': 'อุปกรณ์',
    'web.nav.audit': 'ตรวจสอบ',
    'web.nav.storage': 'พื้นที่จัดเก็บ',
    'web.language.status': 'ภาษาของอินเทอร์เฟซ',
    'web.language.currentPrefix': 'ปัจจุบัน',
    'web.language.commonEntry': 'ตัวเลือกมีภาษาหลักทั่วโลกเพิ่มเติม',
    'web.table.teamMembers': 'สมาชิกทีม',
    'web.source.fixture': 'ข้อมูลสาธิต',
    'web.source.live': 'สแน็ปช็อตสด',
    'web.state.auth.label': 'ต้องการการยืนยันตัวตน',
    'web.state.auth.title': 'เข้าสู่ระบบก่อนดูข้อมูลซิงค์',
    'web.state.auth.message': 'ต้องยืนยันตัวตนก่อนแสดงข้อมูลซิงค์',
    'web.state.empty.label': 'สแน็ปช็อตว่าง',
    'web.state.empty.title': 'ยังไม่มีข้อมูลซิงค์',
    'web.state.empty.message': 'ยังไม่มีข้อมูลซิงค์ของทีม',
    'web.state.error.label': 'สแน็ปช็อตไม่พร้อมใช้งาน',
    'web.state.error.title': 'ไม่สามารถโหลดสแน็ปช็อตผู้ดูแล',
    'web.state.error.message': 'ลองรีเฟรชหรือตรวจสอบ endpoint ที่กำหนดค่า',
    'web.state.loading.label': 'กำลังโหลดสแน็ปช็อต',
    'web.state.loading.title': 'กำลังโหลดแดชบอร์ดผู้ดูแล',
    'web.state.loading.message': 'JoeSSH กำลังดึงข้อมูลสถานะทีม อุปกรณ์ บทบาท และการตรวจสอบ',
    'web.status.current': 'ปัจจุบัน',
    'web.status.catchingUp': 'กำลังซิงค์',
    'web.status.degraded': 'ลดลง',
    'web.status.offline': 'ออฟไลน์',
    'web.status.live': 'สด',
    'web.status.active': 'ใช้งาน',
    'web.status.invited': 'เชิญแล้ว',
    'web.status.suspended': 'ระงับ',
    'web.role.workspaceAdmin': 'ผู้ดูแลพื้นที่ทำงาน',
    'web.role.operator': 'ผู้ปฏิบัติงาน',
    'web.role.supportViewer': 'ผู้ชมฝ่ายสนับสนุน',
    'web.scope.admin': 'สมาชิก บทบาท นโยบายซิงค์',
    'web.scope.operator': 'อุปกรณ์ เซสชัน อ่านการตรวจสอบ',
    'web.scope.viewer': 'แดชบอร์ดอ่านอย่างเดียว',
    'web.risk.full': 'เข้าถึงเต็ม',
    'web.risk.elevated': 'สูง',
    'web.risk.limited': 'จำกัด',
    'web.memberCount.one': 'สมาชิก',
    'web.memberCount.other': 'สมาชิก',
    'web.event.profileChanges': 'ยอมรับ 12 การเปลี่ยนแปลงโปรไฟล์',
    'web.event.freshCursor': 'ออกเคอร์เซอร์ใหม่',
    'web.event.roleChanged': 'เปลี่ยนบทบาท Jordan Lee',
    'web.event.exportBlocked': 'บล็อกการส่งออกจากอุปกรณ์ที่ไม่ได้จัดการ',
    'web.target.supportViewer': 'ผู้ชมฝ่ายสนับสนุน',
    'web.target.unknownBrowser': 'เบราว์เซอร์ที่ไม่รู้จัก',
    'web.error.boundary.title': 'เกิดข้อผิดพลาด',
    'web.error.boundary.reload': 'โหลดใหม่',

    'web.error.boundary.message': '\u0e42\u0e2b\u0e25\u0e14 JoeSSH \u0e43\u0e2b\u0e21\u0e48 \u0e2b\u0e23\u0e37\u0e2d\u0e15\u0e34\u0e14\u0e15\u0e48\u0e2d\u0e1d\u0e48\u0e32\u0e22\u0e2a\u0e19\u0e31\u0e1a\u0e2a\u0e19\u0e38\u0e19\u0e2b\u0e32\u0e01\u0e1b\u0e31\u0e0d\u0e2b\u0e32\u0e22\u0e31\u0e07\u0e04\u0e07\u0e2d\u0e22\u0e39\u0e48',
  },
};

export function getInitialLanguageChoice(): LanguageChoice {
  if (typeof window === 'undefined') {
    return 'auto';
  }

  const params = new URLSearchParams(window.location.search);
  const requested = getLanguageChoice(params.get('lang'));

  if (requested) {
    return requested;
  }

  const stored = readStoredLanguageChoice();

  return getLanguageChoice(stored) ?? 'auto';
}

export function persistLanguageChoice(choice: LanguageChoice) {
  try {
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, choice);
  } catch {
    // Ignore blocked or unavailable storage; the in-memory selection still applies.
  }
}

function readStoredLanguageChoice() {
  try {
    return window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
  } catch {
    return null;
  }
}

export function resolveLanguageChoice(choice: LanguageChoice): AtlasLocale {
  return choice === 'auto' ? detectAtlasLocale(getBrowserLocaleCandidates()) : choice;
}

export function createWebTranslator(locale: AtlasLocale) {
  const shared = createTranslator(locale);

  // Eagerly load the locale bundle so the next render uses full translations.
  void loadLocale(locale).catch(ignoreLocaleLoadFailure);

  return {
    shared,
    local: (key: LocalMessageKey) => localMessages[locale][key] ?? commonMessages[key],
  };
}

export async function createWebTranslatorAsync(locale: AtlasLocale) {
  const shared = await loadSharedTranslator(locale);

  return {
    shared,
    local: (key: LocalMessageKey) => localMessages[locale][key] ?? commonMessages[key],
  };
}

export function getLocalMessageKeys(): LocalMessageKey[] {
  return Object.keys(commonMessages) as LocalMessageKey[];
}

export function applyDocumentLocale(locale: AtlasLocale) {
  document.documentElement.lang = locale;
  document.documentElement.dir = getTextDirection(locale);
}

function getLanguageChoice(value: string | null): LanguageChoice | undefined {
  if (!value || hasUnsafeLanguageChoiceCharacter(value)) {
    return undefined;
  }

  if (value === 'auto') {
    return 'auto';
  }

  return resolveAtlasLocale(value);
}

function hasUnsafeLanguageChoiceCharacter(value: string) {
  for (const character of value) {
    const codePoint = character.codePointAt(0) ?? 0;
    if (/\s/u.test(character) || codePoint <= 31 || (codePoint >= 127 && codePoint <= 159) || /\p{Cf}/u.test(character)) {
      return true;
    }
  }

  return false;
}

async function loadSharedTranslator(locale: AtlasLocale) {
  try {
    return await loadLocale(locale);
  } catch {
    if (locale !== SHARED_FALLBACK_LOCALE) {
      try {
        return await loadLocale(SHARED_FALLBACK_LOCALE);
      } catch {
        return createTranslator(locale);
      }
    }

    return createTranslator(locale);
  }
}

const ignoreLocaleLoadFailure = () => undefined;
